---
- name: Global configurations and security features for new nodes
  hosts: all
  remote_user: rocky
  vars:
    ip_map:
      192.168.1.50: master-1.local.lan
      192.168.1.51: node-1.local.lan
      192.168.1.52: node-2.local.lan

  tasks:
  - name: Expand volumes
    become: yes
    ansible.builtin.shell: sudo rootfs-expand

  # - name: Set authorized key taken from file
  #   ansible.posix.authorized_key:
  #     user: rocky
  #     state: present
  #     key: "{{ lookup('file', '/home/galera/.ssh/nodes.local.lan.pub') }}"

  - name: Change the hostname
    ansible.builtin.hostname:
      name: "{{ ip_map[ansible_default_ipv4.address] }}"
      use: systemd
    when: ansible_default_ipv4.address in ip_map.keys()

  - name: DNF Update all
    dnf:
      name: "*"
      state: latest

  - name: DNF Autoremove
    dnf:
      autoremove: yes
    become: yes

  - name: Replace sshd config with safer defaults
    become: yes
    ansible.builtin.template:
      src: ./roles/common/templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0600'

  - name: Stop ssh service
    become: yes
    ansible.builtin.service:
      name: sshd
      state: stopped

  - name: Start ssh service
    become: yes
    ansible.builtin.service:
      name: sshd
      state: started

  - name: Stop and disable firewalld
    become: yes
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: no

