---
- name: Global configurations and security features Playbook
  hosts: nodes
  remote_user: rocky

  tasks:
  - name: DNF Update all
    dnf:
      name: "*"
      state: latest

  - name: DNF Autoremove
    dnf:
      autoremove: yes
    become: yes

  - name: Replace sshd config with safer defaults
    become: yes
    ansible.builtin.template:
      src: ./roles/common/templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0600'

  - name: Stop ssh service
    become: yes
    ansible.builtin.service:
      name: sshd
      state: stopped

  - name: Start ssh service
    become: yes
    ansible.builtin.service:
      name: sshd
      state: started

  - name: Stop and disable firewalld
    become: yes
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: no
