---
- name: Global configurations and security features for new nodes
  hosts: all
  strategy: free
  remote_user: rocky
  vars:
    ip_map:
      192.168.1.50: master-1.local.lan
      192.168.1.51: node-1.local.lan
      192.168.1.52: node-2.local.lan

  tasks:
  # DEBUG
  # - name: Print all available facts
  #   ansible.builtin.debug:
  #     var: ansible_facts

  - name: Expand volumes
    become: yes
    ignore_errors: yes
    ansible.builtin.shell: rootfs-expand

  - name: Change the hostname
    ansible.builtin.hostname:
      name: "{{ ip_map[ansible_default_ipv4.address] }}"
      use: systemd
    when: ansible_default_ipv4.address in ip_map.keys()

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'


  - name: DNF Update all
    dnf:
      name: "*"
      state: latest

  - name: DNF Autoremove
    dnf:
      autoremove: yes
    become: yes

  - name: Replace sshd config with safer defaults
    become: yes
    ansible.builtin.template:
      src: ./roles/common/templates/sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0600'

  - name: Stop ssh service
    become: yes
    ansible.builtin.service:
      name: sshd
      state: stopped

  - name: Start ssh service
    become: yes
    ansible.builtin.service:
      name: sshd
      state: started

  - name: Stop and disable firewalld
    become: yes
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Enable cgroup via boot commandline if not already enabled for Centos
    lineinfile:
      path: /boot/cmdline.txt
      backrefs: yes
      regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
      line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    notify:
      - Restart machines
      - Wait for the machine to come back online

  handlers:
    - name: Restart machines
      ignore_errors: yes
      command: /sbin/shutdown -r now
      become: yes
      when: ansible_os_family in ['RedHat', 'Rocky']

    - name: Wait for the machine to come back online
      wait_for_connection:
        connect_timeout: 60
        sleep: 5
        delay: 5
        timeout: 300
