---
- name: Test Playbook
  hosts: nodes
  remote_user: galera

  tasks:
  - name: Update package cache
    ansible.builtin.apt:
      update_cache: yes
    become: yes

  - name: Install common software
    ansible.builtin.apt:
      update_cache: no
      pkg:
        - curl
        - net-tools
        - dnsutils
    become: yes

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes
    become: yes


  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes
    become: yes

  - name: Run the equivalent of "apt-get clean" as a separate step
    apt:
      clean: yes
    become: yes

