---
- name: Power off playbook
  hosts: nodes
  remote_user: rocky

  tasks:
  - name: Shutdown command
    command: /sbin/shutdown -h now
    become: yes
    gather_facts: no
    when: ansible_os_family in ['RedHat', 'Rocky']
